#Specify the version of the yml file
version: '3.0'

# here we specify the services, componing the pipeline
services:



  reddit_collector:
    build: ./reddit_collector/
    volumes:
    - ./reddit_collector/:/app
    depends_on:
    - mongodb


  mongodb:
    image: mongo
    ports:
        - 27017:27017
        
  elt_job:
    build: ./etl_job/
    container_name: tahinijob    
    volumes:  
    - ./etl_job/:/app
    depends_on:
    - postgresdb
    - mongodb

  postgresdb:
      image: postgres
      container_name: tahinipost
      ports:
          - 5433:5432
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=reddit_db    
          
  slackbot:
      build: ./slackbot/
      container_name: slackBot
      volumes:
      - ./slackbot/:/app
      depends_on:
      - postgresdb

